DATALOADER:
  TRAIN_X:
    BATCH_SIZE: 32
  TEST:
    BATCH_SIZE: 100
  NUM_WORKERS: 8

INPUT:
  SIZE: (224, 224)
  INTERPOLATION: "bicubic"
  PIXEL_MEAN: [0.48145466, 0.4578275, 0.40821073]
  PIXEL_STD: [0.26862954, 0.26130258, 0.27577711]
  TRANSFORMS: ["random_resized_crop", "random_flip", "normalize"]

OPTIM:
  NAME: "sgd"
  LR: 0.01
  #LR: 0.1
  #MAX_EPOCH: 200
  MAX_EPOCH: 70
  LR_SCHEDULER: "cosine" #"single_step" #"cosine"
  WARMUP_EPOCH: 5 #1
  WARMUP_TYPE: "linear" #"constant"
  WARMUP_CONS_LR: 1e-4 #1e-4 #1e-5
  WEIGHT_DECAY: 0.01

TRAIN:
  PRINT_FREQ: 1

MODEL:
  BACKBONE:
    NAME: "ViT-L/14"

TEST:
  PER_CLASS_RESULT: False

TRAINER:
  CLIP_ADAPTER:
    RATIO: 0.5 #0.2
    WORD_ADAPTER_TYPE: "self_attn" #"linear_residual" #"self_attn" #"linear"
